site_name: "devex-techdocs-experiment"
site_description: "A guide to mobile application development for the Government of the Province of British Columbia"
repo_url: https://github.com/bcgov/developer-experience-techdocs-experimental
edit_uri: edit/main/docs/

nav:
  - Introduction: index.md
  - Project initiation: getting_started.md
  - Distribution Methods: distribution_methods.md
  - Managing Your App: app_management.md
  - Mobile App Development Guide: developer.md
  - Apple App Signing: apple_app_signing.md
  - Google App Signing: google_app_signing.md
  - Google Signing For React Native Apps: google_react_native_signing.md
  - Publish your app: publish.md
  - Encryption Export Regulations: encryption.md
  - Contact Us: contact.md
plugins:
  - techdocs-core